pipeline {
    agent any
    environment {
        DOCKERHUB_PASS = credentials('docker-pass')
        IMAGE_TAG = "${env.BUILD_TIMESTAMP ?: 'latest'}"
    }
    stages {
        stage('Checkout Code') {
            steps {
                script {
                    // Checkout the repository
                    checkout scm
                }
            }
        }
        stage('Debug: List Files') {
            steps {
                script {
                    // List the files in the current workspace to verify Dockerfile existence
                    sh 'ls -la'
                }
            }
        }
        stage('Building the Student Survey Image') {
            steps {
                script {
                    checkout scm
                    sh 'echo ${BUILD_TIMESTAMP}'
                    sh "docker login -u gshieldsgmu -p $DOCKERHUB_PASS_PSW"
                    sh 'docker build -t gshieldsgmu/survey-app:${IMAGE-TAG} -f surveyapp/Dockerfile survey-app'
                }
            }
        }
        stage('Pushing Image to DockerHub') {
            steps {
                script {
                    sh 'docker push gshieldsgmu/survey-app:${IMAGE-TAG}'
                }
            }
        }
        stage('Deploying to Kubernetes') {
            steps {
                sh 'kubectl --kubeconfig=/var/lib/jenkins/.kube/config set image deployment/app container-0=gshieldsgmu/survey-app:${IMAGE_TAG} -n default'

            }
        }
    }
}
