pipeline {
    agent any
    environment {
        DOCKERHUB_PASS = credentials('docker-pass')
        IMAGE_TAG = "${env.BUILD_TIMESTAMP ?: 'latest'}"
        DOCKERHUB_USER = 'gshieldsgmu' // Define DockerHub username as a variable for reuse
    }
    stages {
        stage('Checkout Code') {
            steps {
                script {
                    // Checkout the repository
                    checkout scm
                }
            }
        }
        stage('Debug: List Files') {
            steps {
                script {
                    // List the files in the current workspace to verify Dockerfile existence
                    sh 'ls -la'
                }
            }
        }
        stage('Building the Student Survey Image') {
            steps {
                script {
                    sh "echo ${IMAGE_TAG}"
                    sh "docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS"
                    sh "docker build -t $DOCKERHUB_USER/survey-app:${IMAGE_TAG} -f surveyapp/Dockerfile surveyapp"
                }
            }
        }
        stage('Pushing Image to DockerHub') {
            steps {
                script {
                    sh "docker push $DOCKERHUB_USER/survey-app:${IMAGE_TAG}"
                }
            }
        }
        stage('Deploying to Kubernetes') {
            steps {
                script {
                    sh "kubectl --kubeconfig=/var/lib/jenkins/.kube/config set image deployment/survey-app container-0=$DOCKERHUB_USER/survey-app:${IMAGE_TAG} -n default"
                }
            }
        }
    }
}
